spring:
  application:
    name: xxt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxtweb?serverTimezone=GMT%2B8
    username: root
    password: 123456
  mvc:
    servlet:
      path: /xxt/api
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB

#  main:
#    allow-bean-definition-overriding=true:#server:
#  port: 8080

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.qjn.xiangxi_system.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true

file:
  upload-path: ${user.dir}/upload/images
  access-path: /img/upload/
  upload:
    path: src/main/resources/static/img/upload