spring:
  application:
    name: xxt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxtweb?serverTimezone=GMT%2B8
    username: root
    password: 123456
  mvc:
    servlet:
      path: /xxt/api
      multipart:
        #单个文件设置大小
        max-file-size: 500MB
        #总文件限制大小
        max-request-size: 1024MB
server:
  tomcat:
    max-swallow-size: -1
# 10mb
#  main:
#    allow-bean-definition-overriding=true:#server:
#  port: 8080

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.qjn.xiangxi_system.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true

file:
  upload-path: ${user.dir}/upload/images
  access-path: /img/upload/
  upload:
    path: upload/images
